World: Easter
egg:
  DisplayName: Easter Egg
  Category: Easter
  Description: Return this egg to the Easter Bunny at spawn! He will reward you if you bring him enough easter eggs.
easter_eggs:
- Name: Opened Chocolate Easter Egg
  Id: cbcf8d8f-c79b-4622-907d-6430b8902303
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGM1MGFlZTg4MDEzZThmYWY0MjdlMTlmM2I4OTgyOGI4NmJiZjAzZGQyZjE3YzRjNzYwZDFkZGUyMmRlMyJ9fX0=
- Name: Pink Easter Egg
  Id: bebe7a0e-8287-4fa8-a558-a27a47fb76bd
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzc2NTk1ZWZmY2M1NjI3ZTg1YjE0YzljODgyNDY3MWI1ZWMyOTY1NjU5YzhjNDE3ODQ5YTY2Nzg3OGZhNDkwIn19fQ==
- Name: Rainbow Easter Egg
  Id: 517240fe-7646-465f-bda6-ef8e456e58b4
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjFjOGM1ODZiNGI5NzYxZDhiNzhmMTZlYjU3MzU4MzM3NGU1MmYxYTI4NzM1NzY3NGUzMWZkMmE4MzgyIn19fQ==
- Name: White Easter Egg
  Id: 8ebb484c-a101-4046-ba19-f8a11e170de3
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMjY0NDMwZTQ5M2ZlYjVlYWExNDU1ODJlNTRlNzYxYTg2MDNmYjE2Y2MwZmYxMjY4YTVkMWU4NjRlNmY0NzlmNiJ9fX0=
- Name: Red Easter Egg
  Id: a3c9ff6b-b404-42f5-8db4-197f085bc276
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjNkNjliMjNhZTU5MmM2NDdlYjhkY2ViOWRhYWNlNDQxMzlmNzQ4ZTczNGRjODQ5NjI2MTNjMzY2YTA4YiJ9fX0=
- Name: White Easter Egg
  Id: e8689974-3faa-4d66-90b7-9119947060b6
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGViNWFiYjEyMzUyN2E3YTFmNWM5NTg5NzE1OTY0YjU5Zjc2ODI0OTI2ZDNiOTgyZmE4NDExZDQ2MDZjNzkifX19
- Name: Sunflower Easter Egg
  Id: 73028eb9-2ab9-4bb6-9bfd-a152966b5243
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMWYxOGI5YTQzNmEyN2Y4MTNjMjg3ZWI2NzM3OWVmOGFkYmZkYzcwYWZhZjMwNGM0M2IxNjZjZTk4NmRkOCJ9fX0=
- Name: Creeper Easter Egg
  Id: 20726b71-7df4-4380-a5b7-311ac1aeaa29
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjVkYmVjNTI0YTk1ZGVhNGQ0ZDU4MDJjOTViMGNmNWVhZmViZDMxYTk4NzY3NzI3MTZhNDg2MmQ2Yzg4YSJ9fX0=
- Name: Green Easter Egg
  Id: 259631f6-804d-4ce5-9e67-d47e236728d2
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjJjZDVkZjlkN2YxZmE4MzQxZmNjZTJmM2MxMThlMmY1MTdlNGQyZDk5ZGYyYzUxZDYxZDkzZWQ3ZjgzZTEzIn19fQ==
- Name: Blue Easter Egg
  Id: 2c87257c-c058-4a28-990e-eeeeae44f8d7
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWViMzM1MTgyZGI1ZjNiZTgwZmNjZjZlYWJlNTk5ZjQxMDdkNGZmMGU5ZjQ0ZjM0MTc0Y2VmYTZlMmI1NzY4In19fQ==
- Name: Yellow Easter Egg
  Id: da650cc3-1e74-49a6-80f7-019d7d4e722e
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTdkYWZmNDIzOWU1NjBmN2Y1M2IxY2NiY2ViYzYxNGYwZGRmMzU4MWE2ZmFkNWJkODE1NjcyOTFlY2Y0NTcxIn19fQ==
- Name: Yellow Easter Egg
  Id: 73f9c460-ef07-4bf0-a7c2-c08118937ed6
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDM2ZmU4M2M0MmM2Y2U3Mzg2Y2YyMzMzYTFjNTk1ZDBiNDMzZGE3YmM1NTkyYjg2ODY2ODU1MWQ2OWI5YjAifX19
- Name: Blue Easter Egg
  Id: d2f224f6-fc2a-409f-a094-b058398bdffa
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDY0MmFmYTM5Njg1M2I4MWIxN2JlZjVjOGQ3YTQ0YzEyZGU2ODlhNTZhZjQ3NDg0NjY3OTgzOTlkYTNjZmVhZSJ9fX0=
- Name: Violet Easter Egg
  Id: ba43c4b9-4b23-4f40-8563-79428689d835
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTg4OWYxMWM4ODM4YzA5ZTFlY2YyZjgzNDM5ZWJjYjlmMzI0ZTU2N2IwZTlkYzRiN2MyNWQ5M2U1MGZmMmIifX19
- Name: Orange Easter Egg
  Id: e28bd1f7-e7d3-4f18-b745-e2a53723b22d
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmI4YjJiZGZjNWQxM2I5ZjQ1OTkwZWUyZWFhODJlNDRhZmIyYTY5YjU2YWM5Mjc2YTEzMjkyYjI0YzNlMWRlIn19fQ==
- Name: Pink Easter Egg
  Id: 07117dcf-6869-4f7e-a99c-0b7ce3fd93c9
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTViOGRjYmVhMjdmNDJmNWFlOTEwNDQ1ZTA1ZGFjODlkMzEwYWFmMjM2YTZjMjEyM2I4NTI4MTIwIn19fQ==
- Name: Pink Easter Egg
  Id: cdb2d142-37db-49a4-ba3c-363406f2113a
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNThiOWUyOWFiMWE3OTVlMmI4ODdmYWYxYjFhMzEwMjVlN2NjMzA3MzMzMGFmZWMzNzUzOTNiNDVmYTMzNWQxIn19fQ==
- Name: Rainbow Easter Egg
  Id: bc4c7927-75c6-45cd-8add-b94c9cdf066e
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjU2ZjdmM2YzNTM2NTA2NjI2ZDVmMzViNDVkN2ZkZjJkOGFhYjI2MDA4NDU2NjU5ZWZlYjkxZTRjM2E5YzUifX19
easter_baskets:
- Name: Easter Basket
  Id: d2c1a244-b483-47bb-9488-ceff169ca694
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTJiZjA1ZDNlNzU2YzMzNzk4NzdhOGFjOGZkZmE0NDE4Y2RlNmY1Y2M3ZTk5MTAzYTEyZmY5YWMxNDk5NyJ9fX0=
- Name: Easter Basket
  Id: dab4a0a8-df17-4560-8780-af08a61aa8e0
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGEzZGRjZTJjNTU2ZjIyZmRhMzE3OTc4MzlmZmQxZDA0MjhhZmUxMmE0NWMwNzM1NTk1MWY0NDRjNzc0YWQifX19
- Name: Easter Basket
  Id: d5feb265-82e0-40c7-a873-1d24e3774850
  Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODNjMjVhN2ExODgxOTZiMTg3MTcyNjRmZmU4MzdjYTM0OGNmNzE5ZTgyNzE3OWVkYzRiNzhjYmNiOGM3ZGQ4In19fQ==
items:
- Name: TreeChopper
  Commands:
  - custom give %player% tools:tree_chopper
  Description: The Tree Chopper
- Name: Pokeball
  Commands:
  - custom give %player% pokemob:pokeball 20
  Description: 20 Pokéballs
- Name: Pokeball
  Commands:
  - custom give %player% pokemob:pokeball 10
  Description: 10 Pokéballs
- Name: CustomTNT
  Commands:
  - custom give %player% tnt:mining_tnt 10
  Description: 10 Mining Dynamite
- Name: CustomTNT
  Commands:
  - custom give %player% tnt:woodcutting_tnt 10
  Description: 10 Lumber Bombs
- Name: CustomTNT
  Commands:
  - custom give %player% tnt:kinetic_tnt 5
  Description: 5 Kinetic Blasts
- Name: CustomTNT
  Commands:
  - custom give %player% tnt:power_tnt 5
  Description: 5 Power TNT
- Name: CustomTNT
  Commands:
  - custom give %player% tnt:silk_tnt 10
  Description: 10 Silk Charges
- Name: CustomTNT
  Commands:
  - custom give %player% tnt:pressure_bomb 10
  Description: 10 Pressure Bombs
- Name: CustomTNT
  Commands:
  - custom give %player% tnt:fragmentation_bomb
  Description: 10 Fragmentation Bombs
- Name: CustomTNT
  Commands:
  - custom give %player% tnt:incendiary_bomb
  Description: 10 Incendiary Bombs
- Name: Diamonds
  Commands:
  - give %player% diamond 10
  Description: 10 Diamonds
- Name: Emeralds
  Commands:
  - give %player% emerald 10
  Description: 10 Emeralds
- Name: Eggs
  Commands:
  - give %player% egg 16
  Description: 16 Eggs
- Name: Fireworks
  Commands:
  - give %player% fireworks 20
  Description: 20 Fireworks
rewards:
- Level: 100
  item:
    Name: Elytra
    Description: Elytra
    Commands:
    - give %player% elytra
- Level: 200
  item:
    Name: EggHunterTitle
    Description: Egg Hunter Title
    Commands:
    - titles unlock %player% EggHunter
    - titles set %player% EggHunter
- Level: 300
  item:
    Name: BombBag
    Description: Bomb Bag
    Commands:
    - custom give %player% tnt:bomb_bag
- Level: 400
  item:
    Name: Beacon
    Description: Beacon
    Commands:
    - give %player% beacon
- Level: 500
  item:
    Name: EasterBunnyTitle
    Description: Easter Bunny Title
    Commands:
    - titles unlock %player% EasterBunny
    - titles set %player% EasterBunny
- Level: 600
  item:
    Name: FoolsAxe
    Description: Fools Axe
    Commands:
    - custom give %player% FoolsGold:FoolsAxe
- Level: 700
  item:
    Name: FoolsPick
    Description: Fools Pick
    Commands:
    - custom give %player% FoolsGold:FoolsPick
- Level: 800
  item:
    Name: FoolsSword
    Description: FoolsSword
    Commands:
    - custom give %player% FoolsGold:FoolsSword
- Level: 900
  item:
    Name: FoolsBow
    Description: Fools Bow
    Commands:
    - custom give %player% FoolsGold:FoolsBow
- Level: 1000
  item:
    Name: DragonHead
    Description: Dragon Head
    Commands:
    - give %player% skull 1 5
